### PR TITLE
Added support for Curve and Surface geometry type.

### LINKED ISSUE #3: Add support for GML geometry types - Curve and Surface
Reference from this issue: https://github.com/opengeospatial/ets-wfs20/issues/170

As the geotoolkit version 3.21 is not supporting the Curve and Surface geometry type. The method `calculateEnvelope(NodeList geomNodes)` should be updated to support Curve and Surface type.

### PR DESCRIPTION
**Pull request by keshav-nangare**
Fixed #3.

### CODE REVIEW

**Comment by iuriemaxim** [comment]
It is most probably in relatiin with this bug https://github.com/opengeospatial/ets-wfs20/issues/164 that was closed trough a work around (still the the TEAMEngine is indicating an error, just that the text of the error is mentioning that a manual validation is necessary).

**Comment by dstenger** [comment]
@iuriemaxim Thank you for the feedback. However, isn't opengeospatial/ets-wfs20#164 related to geometry types points and multipoints? Can you please describe your idea more in detail?

**Comment by iuriemaxim** [comment]
@dstenger 

Indeed there are points and multipoints. Spatial join should not be tested only surface with surface, surface with curve, surface with point and surface with curve. And there is no test for point with point and curve with curve.

Looking at the code prior to the pseudo-fix it can be seen that they are three ”DOTO”, and two of them are indicating curve and surface.
image

Based on the above image I supposed that once the support for curve and surface will be available the issue https://github.com/opengeospatial/ets-wfs20/issues/164 can be properly fixed as the message bellow that is provided is treated as an error even if it indicates that a manual validation is necessary.

image


Right now as the TEAMEngine is providing the above error, there is no solution to fix this issue in the INSPIRE Validator https://github.com/inspire-eu-validation/community/issues/209 .

**Comment by ghobona** [comment]
@iuriemaxim  https://github.com/inspire-eu-validation/community/issues/209 is a separate issue, so will be addressed by a separate PR.

@keshav-nangare For now, please complete this PR as suggested by @dstenger in https://github.com/opengeospatial/geomatics-geotk/pull/4#pullrequestreview-472692224.

**Comment by iuriemaxim** [comment]
@ghobona Thank you for taking into account to address the inspire-eu-validation/community#209 issue trough a separate PR.
Should I understand that the issue is actually in relation with geomatics-geotk and this is what the two issues have in common?
For this new PR are any other details needed or any action is expected from me?

**Comment by dstenger** [comment]
@iuriemaxim We decided to skip the test when the geometry type is not supported and created a new issue: https://github.com/opengeospatial/ets-wfs20/issues/175
We hope this solution is fine for you.

**Comment by dstenger** [comment]
The implementation of the fix looks fine.

However, when I test it with the service provided in description of https://github.com/opengeospatial/ets-wfs20/issues/170, all `Spatial filter` tests are skipped.

@carlospzurita @calhanson Has the test service been changed in the last weeks?

**Comment by calhanson** [comment]
> 
> 
> The implementation of the fix looks fine.
> 
> However, when I test it with the service provided in description of [opengeospatial/ets-wfs20#170](https://github.com/opengeospatial/ets-wfs20/issues/170), all `Spatial filter` tests are skipped.
> 
> @carlospzurita @calhanson Has the test service been changed in the last weeks?

The test service has not been changed in the last weeks. I tried running the tests currently on 'https://inspire.ec.europa.eu/validator' and there the 'Spatial filter' tests are verified (and fails as expected due to lack of Curve/Surface support). Are there any new/altered preconditions for those tests?

**Comment by iuriemaxim** [comment]
With this occasion was solved also https://github.com/inspire-eu-validation/community/issues/209

**Pull request merged**
